### ISSUE TITLE
javascripts dont work anymore on managed chromebooks

### ISSUE THREAD

**Issue by caecaelol** [yeahbread/Ego-Menu-Bookmarklets#3]
can you put it as a html file? thank you!!!!

**Comment by yeahbread** [comment]
for sure, here's the static HTML file, unfortunately, since it's an html file, this version won't overlay above the pages the JavaScript is executed on, and is restricted to just your local egoMenu.html tab.
https://github.com/yeahbread/Ego-Menu-Bookmarklets/blob/main/egoMenu.html

simply download the file and double click to run it, it should open in your default browser!
